### ISSUE TITLE
Error in podlove_graph_regression(du, plot_type = "point"

### ISSUE THREAD

**Issue by PechGehabt** [lordyo/podlover#35]
Hi! 

i updated to 1.3.0 - thanks a lot for your work! 

When i run my script it stops with the following message:
```
Quitting from lines 221-224 (auswertung.Rmd) 
Fehler in podlove_graph_regression(du, plot_type = "point") : 
  konnte Funktion "podlove_graph_regression" nicht finden
Ruft auf: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
```

Ausführung angehalten

Line 221-224 are:
```
```{r echo=FALSE}

reg_g <- podlove_graph_regression(du, plot_type = "point")

```
```

**Comment by lordyo** [comment]
Thanks for the feedback. The function `podlove_graph_regression()` was replaced by the function `podlove_plot_regression()`. Type `?podlove_plot_regression` in your RStudio console to check out the documentation.

For your purposes, you don't need to call `downloads_until()` anymore. Instead, use `podlove_plot_regression()`. For an example, check the Regression chapter in the vignette:

https://github.com/lordyo/podlover#regression-analysis-is-your-podcast-gaining-or-losing-listeners
